[theme]
primaryColor = "#2E86AB"       # Cool Blue for interactive elements
backgroundColor = "#FAFAFA"    # Off-white for a clean canvas
secondaryBackgroundColor = "#F4F4F4"  # Light Gray for sections
textColor = "#3D3D3D"          # Charcoal for text readability
font = "sans serif"            # Clean, professional look
